<?php

namespace laabi\appartooBundle\Repository;

/**
 * InsecteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InsecteRepository extends \Doctrine\ORM\EntityRepository
{
}
